import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-light dark:bg-dark text-text-light dark:text-text-dark">
        <Navbar></Navbar>
        <main>{children}</main>
      </body>
    </html>
  );
}
