import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/components/layout/navbar";
import ScrollWrapper from "@/components/ScrollWrapper";
import Background from "@/components/layout/Background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background-light dark:bg-background-dark relative -z-999">
        <div className="fixed inset-0 -z-10">
          <Background />
        </div>
        <main>
          <ScrollWrapper>
            <Navbar />
          </ScrollWrapper>
          {children}
        </main>
      </body>
    </html>
  );
}
